on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: https://pixnyb.github.io
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure GitHub Pages
        id: pages
        uses: actions/configure-pages@v3

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
          bundler-cache: true

      - name: Build with Jekyll
        run: bundle exec jekyll build

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: site
          path: _site

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          artifact_name: site
